SAW/SAW.WebApplication/Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SAW.WebApplication.Controllers
{
    public class MapController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult TianDiTu()
        {
            return View();
        }

        public ActionResult TianDiTuIndex()
        {
            return View();
        }

        #region OpenLayers
        public ActionResult OpenLayers()
        {
            return View();
        }

        public ActionResult OpenLayersIndex()
        {
            return View();
        }

        public ActionResult OpenLayersBingMaps()
        {
            return View();
        }

        public ActionResult OpenLayersRasterReprojection()
        {
            return View();
        }

        public ActionResult LayerClipping()
        {
            return View();
        }

        public ActionResult OpenLayersBMap()
        {
            return View();
        }

        public ActionResult Kriging()
        {
            return View();
        }

        public ActionResult KrigingGZ()
        {
            return View();
        }

        public ActionResult KrigingGZ2()
        {
            return View();
        }

        public ActionResult KrigingChina()
        {
            return View();
        }
        #endregion

        #region BMap
        public ActionResult BMap()
        {
            return View();
        }

        public ActionResult BaiDu()
        {
            return View();
        }

        public ActionResult BaiDuTileLayer()
        {
            return View();
        }

        public ActionResult BaiDuTileLayerTianDiTu()
        {
            return View();
        }

        public ActionResult BMapTranslate()
        {
            return View();
        }
        #endregion

        #region BingMaps
        public ActionResult BingMaps()
        {
            return View();
        }

        public ActionResult BingMapsXYZoom()
        {
            return View();
        }
        #endregion

        #region Leaflet
        public ActionResult Leaflet()
        {
            return View();
        }
        #endregion
    }
}

SAW/SAW.WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("关于", "About", "Home")</li>
                    <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Map <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("天地图", "TianDiTu", "Map")</li>
                            <li role="separator" class="divider"></li>
                            <li>@Html.ActionLink("OpenLayers", "OpenLayers", "Map")</li>
                            <li>@Html.ActionLink("OpenLayers", "OpenLayersIndex", "Map")</li>
                            <li>@Html.ActionLink("OpenLayers", "LayerClipping", "Map")</li>
                            <li role="separator" class="divider"></li>
                            <li>@Html.ActionLink("百度地图", "BaiDu", "Map")</li>
                            <li>@Html.ActionLink("百度地图", "BaiDuTileLayer", "Map")</li>
                            <li>@Html.ActionLink("百度地图", "BaiDuTileLayerTianDiTu", "Map")</li>
                            <li role="separator" class="divider"></li>
                            <li>@Html.ActionLink("BingMaps", "BingMaps", "Map")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>